stages:
  - build
  - update-helm-chart

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CHART_REPO: https://gitlab.com/EagleDevStack/flask-app-helm.git

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - "*.py"
        - "Dockerfile"
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - ".gitignore"
        - ".gitlab-ci.yml"
        - ".github/workflows/main.yml"
        - "README.md"
        - "LICENSE"
        - "requirements.txt"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

build-task:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - >
      docker login $CI_REGISTRY
      -u $CI_REGISTRY_USER 
      -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

update-helm-chart-task:
  stage: update-helm-chart
  image: alpine/git:latest
  variables:
    GIT_STRATEGY: none
  script:
    - git clone $CHART_REPO helm-charts
    - cd helm-charts/charts/flask-app
    - 'sed -i "s|tag:.*|tag\: \"$IMAGE_TAG\"|" values.yaml'
    - 'sed -i "s|appVersion:.*|appVersion: \"$IMAGE_TAG\"|" Chart.yaml'
    - awk '/^version:/ {split($2, v, "."); $2 = v[1] "." v[2] "." v[3]+1} 1' Chart.yaml > Chart.yaml.tmp && mv Chart.yaml.tmp Chart.yaml
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git add .
    - git commit -m "Изменение версии образа на $IMAGE_TAG"
    - git push origin main
